### ISSUE TITLE
Error: Unexpected exception, ReferenceError: id is not defined

### ISSUE THREAD

**Issue by Samurais** [superscriptjs/superscript#297] opened 2016-10-22 02:48 UTC
After updating with the latest commit, get an error.
## Current Behavior

```
[2016-10-22 10:46:24.326] [ERROR] console - Unexpected exception: ReferenceError: id is not defined
[2016-10-22 10:46:24.327] [ERROR] console - Unexpected exception stack: ReferenceError: id is not defined
    at model.UX.userSchema.methods.updateHistory (/logic/superscript/lib/users.js:84:22)
    at /superscript/index.js:107:16
```
## Possible Solution

```

    var cleanId = this.id.replace(/\W/g, '');
```
## Steps to Reproduce (for bugs)

1.
2.
3.
4.
## Your Environment
- Version used: https://github.com/superscriptjs/superscript/commit/3ed767c80da5305e40731f92f26b660318c7c6bb
- Environment name and version:
- Server type and version: NodeJS 6.7
- Operating System and version: Mac OSX

**Comment by benhjames** [comment] 2016-10-31 16:23
Dupe of #299 - closing. :)

**Closed by benhjames** 2016-10-31 16:23 UTC
