### ISSUE TITLE
error: this.user.memory.create is not a function

### ISSUE THREAD

**Issue by Samurais** [superscriptjs/superscript#314] opened 2016-12-23 07:28 UTC
Use **createUserFact** in ss.

```
    + (*)
    % How old are you
    - {keep}  ^createUserFact(basicinfo,age,<cap1>)
```

It throws an error.

## Expected Behavior

It creates a Knowledge in this.user.memory.

## Current Behavior

Get an TypeError.
```
TypeError: this.user.memory.create is not a function
```

Print the **memory** obj out.
```
console.log(this.user.memory)
```
![image](https://cloud.githubusercontent.com/assets/3538629/21448970/3574fcb6-c923-11e6-9140-25af9c797c62.png)

## Possible Solution

After checking the sfacts functions, I think it does not contain this **create** method.
Is it a possible solution ?
```
exports.createUserFact = function(s,v,o,cb) {
  this.user.memory.db.put({"subject": s, "predicate": v, "object": o}, function(){
    cb(null, "");
  })
}
```

## Steps to Reproduce (for bugs)

1. Create a topic and use createUserFact.
2. Trigger the dialogue
3. Catch the error

## Your Environment

* Version used: superscript 2676c06, sfacts 0.2.1.
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): Node.js 6.9.1
* Server type and version: Mac OSX 
* Operating System and version: Mac OSX

**Comment by benhjames** [comment] 2016-12-23 14:16
Dupe of #312 and fixed in v1.0.0 - see https://github.com/superscriptjs/superscript/blob/v1.0.0/src/plugins/user.js#L62 for the internal details.

I'm not sure if we'll be backporting fixes to v0.12 - but you can override the broken function with a copy of the fixed function (above), so it's probably fine in this case.

**Closed by benhjames** 2016-12-23 14:16 UTC
